import { useEffect, useMemo, useState } from 'react';
import { ArrowLeft, RotateCcw, Save, Trash2, AlertTriangle, Plus, X, FolderOpen, ExternalLink, Camera } from 'lucide-react';
import { toast } from 'sonner';
import { CalibrationStatus } from './CalibrationStatus';
import { UpAxisValue } from './UpAxisToggle';

/**
 * The capture.json structure as it lives on disk. We treat unknown keys
 * as opaque "extras" so they survive a round-trip through this editor —
 * preventing accidental data loss if the format gains new fields.
 */
interface CaptureJsonContent {
  // Footage-root location. Two shapes exist: legacy user-imported
  // captures use absolute `ioi_root`; released-dataset captures
  // (generated by the released-dataset capture generator) use `capture_root`
  // expressed as a path relative to the capture.json's parent dir.
  // The editor reads either and preserves whichever was on disk.
  ioi_root?: string;
  capture_root?: string;
  c3d_root?: string | null;
  params_root?: string | null;
  calib?: string;
  use_deviceid?: boolean;
  cam_fps?: number;
  up_axis?: string;            // world up-axis: x|y|z|-x|-y|-z, or "auto"
  vicon_frame_shift?: number;
  cams?: string[];
  // Two shapes coexist in the wild: legacy user-imported captures use
  // `ioi`, released-dataset captures (generated by
  // the released-dataset capture generator) use `name`. The editor reads
  // either and preserves whichever key was on disk when it writes back.
  sequences?: Record<string, { ioi?: string; name?: string }>;
  groups?: { whitelist?: string[] };
  [key: string]: unknown;
}

interface ContentResponse {
  path: string;
  absolutePath: string;
  modified: string;
  content: CaptureJsonContent;
}

interface Props {
  captureName: string;
  /** Absolute or MOUNT_POINT-relative path to the capture.json file. */
  jsonPath: string;
  onBack: () => void;
  onDeleted: () => void;
  onViewTasks?: () => void;
  onViewResults?: () => void;
}

/**
 * Captures management page. Reads the underlying capture.json, lets the
 * user edit every field with a structured form (rather than raw JSON),
 * and writes back through PUT /api/captures/json. Delete removes the
 * file via DELETE; if any tasks reference this capture the captures DB
 * row stays so historical tasks keep resolving.
 */
export function CaptureManage({ captureName, jsonPath, onBack, onDeleted, onViewTasks, onViewResults }: Props) {
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [original, setOriginal] = useState<CaptureJsonContent | null>(null);
  const [draft, setDraft] = useState<CaptureJsonContent | null>(null);
  const [meta, setMeta] = useState<{ path: string; absolutePath: string; modified: string } | null>(null);
  const [saving, setSaving] = useState(false);
  const [deleteOpen, setDeleteOpen] = useState(false);
  const [deleting, setDeleting] = useState(false);

  // ----------------------------------------------------------------
  // Initial load
  // ----------------------------------------------------------------
  useEffect(() => {
    let cancelled = false;
    setLoading(true);
    setError(null);
    fetch(`/api/captures/json?path=${encodeURIComponent(jsonPath)}`)
      .then(async r => {
        if (!r.ok) {
          const err = await r.json().catch(() => ({}));
          throw new Error(err.error || `${r.status} ${r.statusText}`);
        }
        return r.json() as Promise<ContentResponse>;
      })
      .then(d => {
        if (cancelled) return;
        setOriginal(d.content);
        setDraft(structuredClone(d.content));
        setMeta({ path: d.path, absolutePath: d.absolutePath, modified: d.modified });
      })
      .catch(e => { if (!cancelled) setError(String(e.message ?? e)); })
      .finally(() => { if (!cancelled) setLoading(false); });
    return () => { cancelled = true; };
  }, [jsonPath]);

  const isDirty = useMemo(() => JSON.stringify(original) !== JSON.stringify(draft), [original, draft]);

  // Sorted (id, value) pairs for the Sequences editor. Computed here —
  // above the early-return guards — so the hook count stays stable
  // between the first (loading) render and subsequent renders. The
  // null-safe access matches the loading state where `draft` is null.
  const sequenceEntries = useMemo(
    () => Object.entries(draft?.sequences ?? {}).sort(([a], [b]) => a.localeCompare(b)),
    [draft?.sequences]
  );

  if (loading) {
    return (
      <div className="px-6 py-12 text-center text-foreground-muted">Loading capture…</div>
    );
  }
  if (error || !draft || !meta) {
    return (
      <div className="px-6 py-12 max-w-3xl mx-auto">
        <button onClick={onBack} className="inline-flex items-center gap-1.5 text-foreground-muted hover:text-foreground text-sm mb-4">
          <ArrowLeft className="w-4 h-4" />
          Back
        </button>
        <div className="bg-status-failed-bg border border-status-failed/35 rounded-lg p-4 text-status-failed text-sm">
          Failed to load capture: {error}
        </div>
      </div>
    );
  }

  // ----------------------------------------------------------------
  // Field setters — keep the draft mutation in one place.
  // ----------------------------------------------------------------
  const setField = <K extends keyof CaptureJsonContent>(key: K, value: CaptureJsonContent[K]) => {
    setDraft(prev => ({ ...(prev ?? {}), [key]: value }));
  };

  const reset = () => setDraft(structuredClone(original!));

  const save = async () => {
    if (!isDirty) return;
    setSaving(true);
    try {
      const res = await fetch('/api/captures/json', {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ path: meta.path, content: draft }),
      });
      if (res.ok) {
        const data = await res.json();
        setOriginal(structuredClone(draft));
        setMeta(m => (m ? { ...m, modified: data.modified } : m));
        toast.success('Capture saved');
      } else {
        const err = await res.json().catch(() => ({}));
        toast.error(err.error || `Failed to save (${res.status})`);
      }
    } catch (e) {
      console.error(e);
      toast.error('Failed to save. See console.');
    } finally {
      setSaving(false);
    }
  };

  const remove = async () => {
    setDeleting(true);
    try {
      const res = await fetch(`/api/captures/json?path=${encodeURIComponent(meta.path)}`, { method: 'DELETE' });
      if (res.ok) {
        const data = await res.json();
        if (data.dbRowKept) {
          toast.success(`Capture file removed. ${data.tasksAffected} historical task${data.tasksAffected === 1 ? '' : 's'} preserved in the DB.`);
        } else {
          toast.success('Capture removed.');
        }
        onDeleted();
      } else {
        const err = await res.json().catch(() => ({}));
        toast.error(err.error || `Failed to delete (${res.status})`);
        setDeleting(false);
      }
    } catch (e) {
      console.error(e);
      toast.error('Failed to delete. See console.');
      setDeleting(false);
    }
  };

  // Pick the name-key the existing row uses so saves preserve the
  // on-disk schema (released uses `name`, legacy uses `ioi`).
  const seqNameKey = (val: { name?: string; ioi?: string } | undefined): 'name' | 'ioi' =>
    val && val.name !== undefined ? 'name' : 'ioi';

  const setSequence = (key: string, seqName: string) => {
    setDraft(prev => {
      const next = { ...(prev?.sequences ?? {}) };
      const prevVal = next[key];
      const nameKey = seqNameKey(prevVal);
      next[key] = { [nameKey]: seqName };
      return { ...(prev ?? {}), sequences: next };
    });
  };
  const removeSequence = (key: string) => {
    setDraft(prev => {
      const next = { ...(prev?.sequences ?? {}) };
      delete next[key];
      return { ...(prev ?? {}), sequences: next };
    });
  };
  const addSequence = () => {
    setDraft(prev => {
      const existing = Object.keys(prev?.sequences ?? {}).map(k => parseInt(k, 10)).filter(n => !isNaN(n));
      const nextId = (existing.length === 0 ? 0 : Math.max(...existing) + 1).toString().padStart(3, '0');
      // Match the schema of the existing rows so a capture stays
      // uniformly `name`-shaped or `ioi`-shaped. Default to `ioi` when
      // there are no rows yet — matches the GUI's generate-capture path.
      const sample = Object.values(prev?.sequences ?? {})[0];
      const nameKey = seqNameKey(sample);
      return {
        ...(prev ?? {}),
        sequences: {
          ...(prev?.sequences ?? {}),
          [nextId]: { [nameKey]: '' },
        },
      };
    });
  };

  return (
    <div className="px-6 py-8">
      <div className="max-w-4xl mx-auto">
        {/* Header */}
        <div className="mb-6">
          <button onClick={onBack} className="inline-flex items-center gap-1.5 text-foreground-muted hover:text-foreground text-sm mb-4 transition-colors">
            <ArrowLeft className="w-4 h-4" />
            All captures
          </button>
          <div className="flex items-end justify-between gap-4 flex-wrap">
            <div>
              <h2 className="text-3xl text-foreground tracking-tight font-medium mb-1 flex items-center gap-2">
                <Camera className="w-6 h-6 text-primary" />
                {captureName}
              </h2>
              <div className="text-foreground-subtle text-xs font-mono mt-1 truncate" title={meta.absolutePath}>{meta.absolutePath}</div>
              <div className="text-foreground-faint text-xs mt-0.5">Last modified {meta.modified}</div>
            </div>
            <div className="flex items-center gap-2 flex-wrap">
              {onViewTasks && (
                <button
                  onClick={onViewTasks}
                  className="inline-flex items-center gap-1.5 px-3 py-1.5 text-sm text-foreground-muted hover:text-foreground rounded-md border border-border hover:border-border-strong transition-colors"
                >
                  Tasks <ExternalLink className="w-3 h-3" />
                </button>
              )}
              {onViewResults && (
                <button
                  onClick={onViewResults}
                  className="inline-flex items-center gap-1.5 px-3 py-1.5 text-sm text-foreground-muted hover:text-foreground rounded-md border border-border hover:border-border-strong transition-colors"
                >
                  Results <ExternalLink className="w-3 h-3" />
                </button>
              )}
            </div>
          </div>
        </div>

        {/* Save bar */}
        <div className="sticky top-14 z-10 bg-background/85 backdrop-blur-md border-b border-border-subtle py-2 mb-6 flex items-center justify-between gap-2 flex-wrap">
          <div className="text-xs">
            {isDirty ? (
              <span className="inline-flex items-center gap-1.5 px-2 py-0.5 rounded-full text-[11px] uppercase tracking-wider bg-status-pending-bg border border-status-pending/35 text-status-pending">
                Unsaved changes
              </span>
            ) : (
              <span className="text-foreground-subtle">No changes</span>
            )}
          </div>
          <div className="flex items-center gap-2">
            <button
              onClick={() => setDeleteOpen(o => !o)}
              className="inline-flex items-center gap-1.5 px-3 py-1.5 text-sm text-status-failed hover:opacity-80 rounded-md border border-status-failed/30 hover:border-status-failed/55 transition-colors"
            >
              <Trash2 className="w-3.5 h-3.5" />
              Delete
            </button>
            {isDirty && (
              <button
                onClick={reset}
                disabled={saving}
                className="inline-flex items-center gap-1.5 px-3 py-1.5 text-sm text-foreground-muted hover:text-foreground rounded-md border border-border hover:border-border-strong transition-colors"
              >
                <RotateCcw className="w-3.5 h-3.5" />
                Reset
              </button>
            )}
            <button
              onClick={save}
              disabled={!isDirty || saving}
              className="inline-flex items-center gap-1.5 px-3 py-1.5 bg-primary text-primary-foreground hover:opacity-90 disabled:opacity-40 disabled:cursor-not-allowed text-sm font-medium rounded-md transition-opacity shadow-sm shadow-black/30"
            >
              <Save className="w-3.5 h-3.5" />
              {saving ? 'Saving…' : 'Save changes'}
            </button>
          </div>
        </div>

        {/* Delete confirmation */}
        {deleteOpen && (
          <div className="bg-surface-1 border border-status-failed/40 rounded-lg p-4 mb-6">
            <div className="text-foreground text-sm font-medium flex items-center gap-2 mb-2">
              <AlertTriangle className="w-4 h-4 text-status-failed" />
              Delete this capture?
            </div>
            <div className="text-foreground-muted text-xs mb-3 leading-relaxed">
              The file <code className="font-mono text-foreground">{meta.absolutePath}</code> will be removed.
              Historical runs against this capture remain readable — their frozen run configs in <code className="font-mono">run_configs/</code> are unaffected. New runs against this capture will no longer be submittable.
            </div>
            <div className="flex items-center justify-end gap-2">
              <button
                onClick={() => setDeleteOpen(false)}
                className="px-3 py-1.5 text-xs text-foreground-muted hover:text-foreground rounded-md border border-border hover:border-border-strong transition-colors"
              >
                Cancel
              </button>
              <button
                onClick={remove}
                disabled={deleting}
                className="inline-flex items-center gap-1.5 px-3 py-1.5 bg-status-failed/90 hover:bg-status-failed text-white disabled:opacity-40 disabled:cursor-not-allowed text-xs font-medium rounded-md transition-colors"
              >
                <Trash2 className="w-3 h-3" />
                {deleting ? 'Deleting…' : 'Delete capture'}
              </button>
            </div>
          </div>
        )}

        {/* Sources */}
        <Section title="Sources" subtitle="Where the raw input footage (images or videos) and calibration live on disk.">
          {(() => {
            // Released captures store `capture_root` (a path relative to
            // this JSON file). Legacy / user-imported captures store
            // `ioi_root` (absolute). Render whichever exists and write
            // back to the same key so the on-disk schema is preserved.
            const usesCaptureRoot = draft.capture_root !== undefined;
            const rootKey: 'capture_root' | 'ioi_root' = usesCaptureRoot ? 'capture_root' : 'ioi_root';
            const rootVal = (usesCaptureRoot ? draft.capture_root : draft.ioi_root) ?? '';
            const placeholder = usesCaptureRoot
              ? '../../../data/<dataset>'
              : '/path/to/footage_root';
            const label = usesCaptureRoot ? 'Footage root (relative)' : 'Footage root';
            return (
              <Field
                label={label}
                value={rootVal}
                placeholder={placeholder}
                mono
                onChange={v => setField(rootKey, v)}
                icon={<FolderOpen className="w-3.5 h-3.5" />}
              />
            );
          })()}
          <pre className="text-foreground-faint text-[11px] font-mono leading-relaxed bg-surface-2/40 border border-border-subtle rounded-md p-2.5 mt-1 whitespace-pre overflow-x-auto">
{`footage_root/
├── sequence_01/        ← one folder per sequence
│   ├── cam01/          ← per camera: either a folder of frames…
│   │   ├── 0001.jpg     (.jpg / .png / …)
│   │   └── …
│   └── cam02.mp4       …or a single video file (.mp4 / .mov / …)
└── sequence_02/`}
          </pre>
          <Field
            label="Calibration"
            value={draft.calib ?? ''}
            placeholder="/path/to/calib.yaml"
            mono
            onChange={v => setField('calib', v)}
            icon={<FolderOpen className="w-3.5 h-3.5" />}
          />
          <CalibrationStatus
            calibPath={draft.calib ?? ''}
            baseDir={meta?.absolutePath ? meta.absolutePath.replace(/\/[^/]*$/, '') : undefined}
            upAxis={(draft.up_axis as UpAxisValue) ?? 'auto'}
            onUpAxisChange={(v) => setField('up_axis', v)}
          />
        </Section>

        {/* Cameras */}
        <Section
          title="Cameras"
          subtitle={`${(draft.cams ?? []).length} camera${(draft.cams ?? []).length === 1 ? '' : 's'}.`}
        >
          <ArrayField
            values={draft.cams ?? []}
            onChange={list => setField('cams', list)}
            placeholder="IOI_01"
            mono
          />
          {(draft.cams ?? []).length === 0 && (
            <div className="text-foreground-faint text-[11px] italic mt-2">
              Leave empty to auto-detect cameras from the first sequence's folders inside the footage root.
            </div>
          )}
        </Section>

        {/* Sequences */}
        <Section
          title="Sequences"
          subtitle={`${sequenceEntries.length} sequence${sequenceEntries.length === 1 ? '' : 's'}. Add or remove rows; the id (left) is preserved across edits.`}
        >
          <div className="space-y-2">
            {sequenceEntries.map(([key, val]) => (
              <div key={key} className="grid grid-cols-[5rem_1fr_2.5rem] gap-2 items-center">
                <div className="text-foreground-subtle text-xs font-mono px-2 py-1.5 bg-surface-2 border border-border-subtle rounded-md">{key}</div>
                <input
                  type="text"
                  value={val.name ?? val.ioi ?? ''}
                  onChange={e => setSequence(key, e.target.value)}
                  placeholder="sequence_name"
                  className="bg-surface-2 border border-border rounded-md px-2.5 py-1.5 text-foreground text-xs font-mono focus:outline-none focus:border-primary/60 focus:ring-2 focus:ring-primary/20 transition-colors placeholder:text-foreground-faint"
                />
                <button
                  onClick={() => removeSequence(key)}
                  className="inline-flex items-center justify-center text-foreground-subtle hover:text-status-failed border border-border rounded-md hover:border-status-failed/50 transition-colors py-1.5"
                  title="Remove sequence"
                >
                  <X className="w-3.5 h-3.5" />
                </button>
              </div>
            ))}
            <button
              onClick={addSequence}
              className="inline-flex items-center gap-1 px-2.5 py-1 text-[11px] text-foreground-muted hover:text-foreground border border-border rounded-md hover:border-border-strong transition-colors"
            >
              <Plus className="w-3 h-3" />
              Add sequence
            </button>
          </div>
        </Section>

        {/* Capture metadata. Other capture.json keys (groups,
            vicon_frame_shift, etc.) are still preserved on save — the
            editor just doesn't surface them since most users never
            touch them. */}
        <Section title="Capture metadata" subtitle="Recording parameters used by the pipeline.">
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
            <Field
              label="Camera FPS"
              value={String(draft.cam_fps ?? '')}
              placeholder="30"
              type="number"
              mono
              onChange={v => setField('cam_fps', v === '' ? undefined : Number(v))}
            />
          </div>
        </Section>

      </div>
    </div>
  );
}

// ====================================================================
// Layout primitives
// ====================================================================

function Section({ title, subtitle, children }: { title: string; subtitle?: string; children: React.ReactNode }) {
  return (
    <section className="bg-surface-1 border border-border-subtle rounded-xl p-5 mb-5 shadow-sm shadow-black/30 ring-1 ring-inset ring-white/[0.02]">
      <div className="mb-4">
        <h3 className="text-foreground text-base font-medium tracking-tight">{title}</h3>
        {subtitle && <p className="text-foreground-muted text-xs mt-0.5">{subtitle}</p>}
      </div>
      <div className="space-y-3">{children}</div>
    </section>
  );
}

function Field({
  label, value, onChange, placeholder, mono, type = 'text', icon,
}: {
  label: string;
  value: string;
  onChange: (v: string) => void;
  placeholder?: string;
  mono?: boolean;
  type?: 'text' | 'number';
  icon?: React.ReactNode;
}) {
  return (
    <div>
      <div className="flex items-center gap-1.5 text-[10px] uppercase tracking-wider text-foreground-subtle font-medium mb-1">
        {icon}
        {label}
      </div>
      <input
        type={type}
        value={value}
        onChange={e => onChange(e.target.value)}
        placeholder={placeholder}
        className={`w-full bg-surface-2 border border-border rounded-md px-2.5 py-1.5 text-foreground text-sm focus:outline-none focus:border-primary/60 focus:ring-2 focus:ring-primary/20 transition-colors placeholder:text-foreground-faint ${mono ? 'font-mono text-xs' : ''}`}
      />
    </div>
  );
}

function ArrayField({
  values, onChange, placeholder, mono,
}: {
  values: string[];
  onChange: (v: string[]) => void;
  placeholder?: string;
  mono?: boolean;
}) {
  return (
    <div className="space-y-1.5">
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-1.5">
        {values.map((v, i) => (
          <div key={i} className="flex gap-1.5">
            <input
              type="text"
              value={v}
              onChange={e => {
                const next = [...values];
                next[i] = e.target.value;
                onChange(next);
              }}
              placeholder={placeholder}
              className={`flex-1 min-w-0 bg-surface-2 border border-border rounded-md px-2.5 py-1.5 text-foreground text-xs focus:outline-none focus:border-primary/60 focus:ring-2 focus:ring-primary/20 transition-colors placeholder:text-foreground-faint ${mono ? 'font-mono' : ''}`}
            />
            <button
              type="button"
              onClick={() => onChange(values.filter((_, idx) => idx !== i))}
              className="px-2 text-foreground-subtle hover:text-status-failed border border-border rounded-md hover:border-status-failed/50 transition-colors flex-shrink-0"
              title="Remove"
            >
              <X className="w-3 h-3" />
            </button>
          </div>
        ))}
      </div>
      <button
        type="button"
        onClick={() => onChange([...values, ''])}
        className="inline-flex items-center gap-1 px-2.5 py-1 text-[11px] text-foreground-muted hover:text-foreground border border-border rounded-md hover:border-border-strong transition-colors"
      >
        <Plus className="w-3 h-3" />
        Add
      </button>
    </div>
  );
}
